import type { Metadata } from 'next';
import '../styles/globals.css';
// import MenuLateral from './../components/template/MenuLateral';
import { AppProvider } from '@/data/context/AppContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
